const ACTIONS = {
  SHOW_ALL_RECIPE: "SHOW_ALL_RECIPE",
  LOADING: "LOADING",
  CATEGORIES_LIST: "CATEGORIES_LIST",
  SINGLE_RECIPE_INFO: "SINGLE_RECIPE_INFO",
  FAV_RECIPES: "FAV_RECIPES",
  DELETE_FAV_RECIPE: "DELETE_FAV_RECIPE",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
  HIDE_NOTIFICATION: "HIDE_NOTIFICATION",
};

export default ACTIONS;
